const sentenceData = {
  word: {
    clinical: [
      { en: "PI", ja: "治験責任医師" },
      { en: "clinical trial", ja: "臨床試験" },
      { en: "PRT", ja: "治験実施計画書" },
      { en: "IRB", ja: "治験審査委員会" },
      { en: "double-blind study", ja: "二重盲検試験" },
      { en: "Randomized Controlled Trial", ja: "無作為化比較試験" },
      { en: "overall survival", ja: "全生存期間" },   
      { en: "general information", ja: "概要" },
      { en: "background information", ja: "背景情報" },
      { en: "primary endpoint", ja: "主要評価項目" },
      { en: "secondary endpoint", ja: "副次評価項目" },
      { en: "IP", ja: "治験薬" },
      { en: "subject inclusion", ja: "被験者の選択" },
      { en: "subject exclusion", ja: "被験者の除外" },
      { en: "subject withdrawal criteria", ja: "被験者の中止基準" },
      { en: "assessment of efficacy", ja: "有効性の評価" },
      { en: "assessment of safety", ja: "安全性の評価" },
      { en: "statistics", ja: "統計解析" },
      { en: "SDV", ja: "原データの直接閲覧" },
      { en: "deviation", ja: "逸脱" },
      { en: "query", ja: "照会" },
      { en: "audit", ja: "監査" },
      { en: "methodology", ja: "方法" },
      { en: "discontinuation", ja: "医学判断での中止" },
      { en: "withdrawal", ja: "被験者都合含む中止" },
      { en: "serious", ja: "重篤な" },
      { en: "verification", ja: "確認" },
      { en: "window", ja: "許容期間" },
      { en: "study period", ja: "研究期間" },
      { en: "population", ja: "対象集団" },
      { en: "sample size", ja: "目標症例数" },
      { en: "setting", ja: "実施環境" },
      { en: "arm", ja: "群" },
      { en: "comparator", ja: "比較対照" },
      { en: "childbearing potential", ja: "妊娠の可能性" },
      { en: "concomitant therapy", ja: "併用療法" },
      { en: "concomitant medication", ja: "併用薬" },
      { en: "current medical history", ja: "現病歴" },
      { en: "date of visit", ja: "来院日" },
      { en: "dosing record", ja: "服薬記録" },
      { en: "eligibility", ja: "適格性" },
      { en: "race", ja: "人種" },
      { en: "subject", ja: "被験者" },
      { en: "target-lesion", ja: "標的病変" },
      { en: "tumor assessment", ja: "腫瘍評価" },
      { en: "brand name", ja: "商品名" },
      { en: "combination product", ja: "配合剤" },
      { en: "dose change", ja: "容量変更" },
      { en: "dose administered", ja: "投与量" },
      { en: "end date", ja: "終了日" },
      { en: "frequency", ja: "頻度" },
      { en: "generic name", ja: "一般名" },
      { en: "indication for use", ja: "使用理由" },
      { en: "route", ja: "投与経路" },
      { en: "start date", ja: "開始日" },
      { en: "CRF", ja: "症例報告書" },
      { en: "eCOA", ja: "電子臨床転帰評価" },
      { en: "EOT", ja: "投与終了" },
      { en: "ICF", ja: "同意説明文書" },
      { en: "IB", ja: "治験薬概要書" },
      { en: "WOCBP", ja: "妊娠可能な女性" },
      { en: "IRT", ja: "自動応答技術" },
      { en: "DILI", ja: "薬剤性肝障害" },
      { en: "FPI", ja: "最初の患者登録" },
      { en: "LPI", ja: "最後の患者登録" },
      { en: "ICH", ja: "医薬品規制調和国際会議" },
      { en: "EDC", ja: "電子的臨床検査情報収集システム" },
      { en: "GCP", ja: "医薬品の臨床試験の実施に関する手順" }
  
    ],


    disease: [
      { en: "diabetes", ja: "糖尿病" },
      { en: "cancer", ja: "がん" },
      { en: "pneumonia", ja: "肺炎" },
      { en: "asthma", ja: "喘息" },
      { en: "stroke", ja: "脳卒中" },
      { en: "arthritis", ja: "関節炎" },
      { en: "depression", ja: "うつ病" },
      { en: "interstitinal lung disease", ja: "間質性肺疾患" },
      { en: "arteriosclerosis", ja: "動脈硬化症" },
      { en: "hyperlipidemia", ja: "高脂血症" },
      { en: "myocardial infarction", ja: "心筋梗塞" },
      { en: "hepatitis", ja: "肝炎" },
      { en: "gastric ulcer", ja: "胃潰瘍" },
      { en: "cholelithiasis", ja: "胆石症" },
      { en: "osteoporosis", ja: "骨粗鬆症" },
      { en: "bipolar disorder", ja: "双極性障害" },
      { en: "dementia", ja: "認知症" },
      { en: "insomnia", ja: "不眠症" },
      { en: "schizophrenia", ja: "統合失調症" },
      { en: "brain death", ja: "脳死" },
      { en: "cerebral aneurysm", ja: "脳腫瘍" },
      { en: "cerebral hemorrhage", ja: "脳出血" },
      { en: "cerebral infarction", ja: "脳梗塞" },
      { en: "epilepsy", ja: "てんかん" },
      { en: "meningitis", ja: "髄膜炎" },
      { en: "paralysis", ja: "麻痺" },
      { en: "dysmenorrhea", ja: "月経困難症" },
      { en: "endometriosis", ja: "子宮内膜症" }


    ],

    symptom: [
      { en: "cough", ja: "咳" },
      { en: "sore throat", ja: "喉の痛み" },
      { en: "nausea", ja: "吐き気" },
      { en: "rash", ja: "発疹" },
      { en: "fatigue", ja: "疲労" },
      { en: "ache", ja: "疼痛" },
      { en: "appetite loss", ja: "食欲不振" },
      { en: "anxiety", ja: "不安" },
      { en: "bleeding", ja: "出血" },
      { en: "bloodshot", ja: "目の充血" },
      { en: "bloody stool", ja: "血便" },
      { en: "bloody urine", ja: "血尿" },
      { en: "breathlessness", ja: "息切れ" },
      { en: "ringing", ja: "耳鳴り" },
      { en: "chest tightness", ja: "胸部圧迫感" },
      { en: "complaint", ja: "病訴" },
      { en: "constricting pain", ja: "締め付けられるような痛み" },
      { en: "convulsion", ja: "痙攣" },
      { en: "cramping", ja: "締め付けられるような痛み" },
      { en: "cyanosis", ja: "チアノーゼ" },
      { en: "dehydration", ja: "脱水" },
      { en: "delirium", ja: "せん妄" },
      { en: "delusion", ja: "妄想" },
      { en: "depressed", ja: "抑うつの" },
      { en: "deterioration", ja: "悪化" },
      { en: "dyspnea", ja: "呼吸困難" },
      { en: "difficulty swallowing", ja: "嚥下困難" },
      { en: "difficulty urinating", ja: "排尿困難" },
      { en: "discomfort", ja: "不快感" },
      { en: "disorientation", ja: "失見当識" },
      { en: "dizziness", ja: "めまい" },
      { en: "dry cough", ja: "乾性咳嗽" },
      { en: "otalgia", ja: "耳痛" },
      { en: "vomiting", ja: "嘔吐" },
      { en: "eye mucus", ja: "目やに" },
      { en: "fainting", ja: "意識消失" },
      { en: "fever", ja: "発熱" },
      { en: "flatus", ja: "腸内ガス" },
      { en: "stomachache", ja: "胃痛" },
      { en: "genital bleeding", ja: "性器出血" },
      { en: "head congestion", ja: "頭重感" },
      { en: "headache", ja: "頭痛" },
      { en: "heartburn", ja: "胸やけ" },
      { en: "hematemesis", ja: "吐血" },
      { en: "hemoptysis", ja: "喀血" },
      { en: "hiccup", ja: "しゃっくり" },
      { en: "hoarseness", ja: "嗄声" },
      { en: "jaundice", ja: "黄疸" },
      { en: "incontinence", ja: "失禁" },
      { en: "internal bleeding", ja: "内出血" },
      { en: "arthralgia", ja: "関節痛" },
      { en: "lightheadedness", ja: "立ちくらみ" },
      { en: "loose bowels", ja: "下痢" },
      { en: "malaise", ja: "不調" },
      { en: "melena", ja: "黒色便" },
      { en: "migraine", ja: "片頭痛" },
      { en: "nasal congestion", ja: "鼻閉" },
      { en: "numbness", ja: "しびれ" },
      { en: "shivering", ja: "震え" },
      { en: "shooting pain", ja: "電撃痛" },
      { en: "sneeze", ja: "くしゃみ" },
      { en: "snore", ja: "いびき" },
      { en: "sore", ja: "ただれ" },
      { en: "stiff shoulder", ja: "肩こり" },
      { en: "stiffness", ja: "こわばり" },
      { en: "wheezing", ja: "喘鳴" },
      { en: "subjective symptom", ja: "自覚症状" },
      { en: "sweating", ja: "発汗" },
      { en: "swell", ja: "腫れる" },
      { en: "tenderness", ja: "圧痛" },
      { en: "thirst", ja: "口渇" },
      { en: "scarring", ja: "瘢痕" },
      { en: "mucous membrane", ja: "粘膜" },
      { en: "alopecia", ja: "脱毛症" },
      { en: "dyspigmentation", ja: "色素異常" },
      { en: "upset stomach", ja: "胃のむかつき" }
     
    ],

    treatment: [
      { en: "diagnosis", ja: "診断" },
      { en: "treatment", ja: "治療" },
      { en: "prescription", ja: "処方箋" },
      { en: "recovery", ja: "回復" },
      { en: "checkup", ja: "健康診断" },
      { en: "urinalysis", ja: "尿検査" },
      { en: "hematological test", ja: "血液学的検査" },
      { en: "intramuscular injection", ja: "筋肉内注射" },
      { en: "intravenous injection", ja: "静脈注射" },
      { en: "oral administration", ja: "経口投与" },
      { en: "subcutaneous injection", ja: "皮下注射" },
      { en: "topical administration", ja: "局所投与" },
      { en: "N/A", ja: "該当なし" },
      { en: "Not done", ja: "未判定" },
      { en: "Absence", ja: "なし" },
      { en: "ongoing", ja: "継続中" },
      { en: "NOS", ja: "詳細不明" },
      { en: "unit", ja: "単位" },
      { en: "b.i.d", ja: "一日二回" },
      { en: "qd", ja: "一日一回" },
      { en: "q.i.d", ja: "一日四回" },
      { en: "mal", ja: "～回" },
      { en: "a.c", ja: "食前" },
      { en: "p.c", ja: "食後" },
      { en: "v.d.E", ja: "食前" },
      { en: "n.d.E", ja: "食後" },
      { en: "i.c", ja: "食間" },
      { en: "z.d.E", ja: "食間" },
      { en: "h.s", ja: "就寝前" },
      { en: "p.r.n", ja: "頓服" },
      { en: "t.i.d", ja: "一日三回" }


    ]
  },

  query: [
  { ja: "「確認し更新しました」", en: "Confirmed and updated." },
  { ja: "「修正不要」", en: "No change required." },
  { ja: "「確認後に回答します」", en: "We will provide an update once confirmed." },
  { ja: "「原資料に基づき入力を更新しました」", en: "The entry has been updated based on source documents." },
  { ja: "「更新後の記録をご確認ください」", en: "Please refer to the updated record." },
  { ja: "「臨床的意義なし」", en: "No clinical significance." },
  { ja: "「原疾患によるもの」", en: "Due to desease." },
  { ja: "「合併症によるもの」", en: "Due to complications." },
  { ja: "「有害事象によるもの」", en: "Due to adverse events." },
  { ja: "「治験薬との関連あり」", en: "Related to the investigational product." }

  ]
};
